- hosts: all
  become: yes
  tasks:
    - name: disable SELinux
      command: setenforce 0
      ignore_errors: yes

    - name: disable SELinux on reboot
      selinux:
        state: disabled

    - name: disable swap
      command: /usr/sbin/swapoff -a

    - name: remove swap from fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: 'swap\s'

    - name: add Docker YUM repository
      yum_repository:
        name: docker-ce
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: install docker-ce
      yum:
        name: docker-ce-18.06.1.ce-3.el7.x86_64
        state: present
        update_cache: yes

    - name: install docker-py
      yum:
        name: docker-python
        state: present
        update_cache: yes

    - name: start & enable Docker daemon
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: add Kubernetes YUM repository
      yum_repository:
        name: kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      
    - name: install kubelet
      yum:
        name: kubelet-1.12.4-0.x86_64
        state: present
        update_cache: yes

    - name: start & enable kubelet daemon
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: install kubectl
      yum:
        name: kubectl-1.12.4-0.x86_64
        state: present
        update_cache: yes

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        sysctl_file: /etc/sysctl.d/k8s.conf

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        sysctl_file: /etc/sysctl.d/k8s.conf

    - name: install kubeadm
      yum:
        name: kubeadm-1.12.4-0.x86_64
        state: present

    - name: install keepalived
      yum:
        name: keepalived
        state: present

